[phases.setup]
nixPkgs = [
  "php84",
  "php84Packages.composer",
  "nodejs_22"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "rm -rf node_modules package-lock.json public/build",
  "npm install",
  "npm run build",
  "php artisan config:clear",
  "php artisan cache:clear",
  "php artisan view:clear",
  "php artisan migrate --force"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
